@startuml
package ユーザー追加{
    object 追加{
        - ユーザーID
        - 名前
        - メールアドレス
        - パスワード
        - スキル
        - 経歴
        - 自己紹介
    }
    object career{
        - 詳細
        - 西暦from
        - 西暦to

    }
    object skill{
        - タグネーム
        - 評価
        - 年数
    }
    note top of 追加
        - ユーザ-
        - 必須項目
            - 名前: 255文字以内(ユニーク)
            - メールアドレス: 255文字以内
            - パスワード: 12文字以上,英数字それぞれ最低1文字以上
        - 任意項目
            - 自己紹介: 2000字以内
end note

note left of career
        - 経歴(複数)
            - 詳細: 1000字以内
            - 西暦from: 1970年以上のint型
            - 西暦to: 1970年以上のint型、西暦fromよりも大きい数字

end note

note right of skill
  スキル(複数)
        - タグ名(選択式、記入どちらもOK)
        - 評価: 1~5　1つ以上
        - 年数: ０以上のint型(5年まで)
end note
}

package ユーザー更新{
    object 更新{
        - ユーザーID
        - 名前
        - メールアドレス
        - パスワード
        - スキル
        - 経歴
        - 自己紹介
    }
    object updateCareer{
        - 詳細
        - 西暦from
        - 西暦to

    }
    object updateSkill{
        - タグネーム
        - 評価
        - 年数
    }
    note top of 更新
        - ユーザ-
        - 必須項目
            - 名前: 255文字以内(ユニーク)
            - メールアドレス: 255文字以内
            - パスワード: 12文字以上,英数字それぞれ最低1文字以上
        - 任意項目
            - 自己紹介: 2000字以内

end note

note left of updateCareer
- 経歴(複数)
        - 詳細: 1000字以内
        - 西暦from: 1970年以上のint型
        - 西暦to: 1970年以上のint型、西暦fromよりも大きい数字

end note

note right of updateSkill
  スキル(複数)
        - タグ名(選択式、記入どちらもOK)
        - 評価: 1~5　1つ以上
        - 年数: ０以上のint型(5年まで)
end note
}

package メンター募集作成集約{
    object メンター募集{
        - ユーザーID
        - タイトル
        - カテゴリ
        - 相談形式
        - 相談方式
        - デスクプリプション
        - 予算
        - 応募期間
        - メンターID
    }
    note left of メンター募集
        - タイトル: 255文字以内
        - カテゴリ(1つ)
            - プログラミング
            - マーケティング
            - デザイン
            - ライティング
            - 動画・映像
            - ビジネス
            - 語学
            - ライフスタイル
        - 相談形式
            - 単発
            - 継続
        - 相談方式
            - チャット
            - ビデオ通話
        - ディスクリプション(2000文字)
        - 予算(from円~to円)
            - 1000円以上の数値
        - 応募期間
            - 1日単位
            - 最大14日後まで可能
        - ステータス(公開or中止)
        - タグ(複数OK、選択式、記入どちらもOK)
    end note
}

package メンター提案集約{
    object メンター提案{
        - 募集ID
        - メンターID
        - ユーザーID
        - 提案内容
    }
    note right of メンター提案
        - 提案内容: 2000文字以内
        - 提案できるのはスキルを5個以上持つユーザのみ
    end note

}

package プラン集約{
    object プラン作成{
        - ユーザーID
        - タイトル
        - カテゴリ
        - タグ
        - 内容
        - ステータス
        - 相談形式
        - 金額
        - 相談方式
        - メンターID
    }
    note left of プラン作成
        - タイトル: 255文字以内
        - カテゴリ(1つ)
            - 上記のカテゴリ参照
        - タグ(5個まで)
            - 選択式
            - 新規記入
        - 内容
            - 2000文字以内
        - ステータス
            - 公開or中止
        - 相談形式
            - 単発
            - 継続
        - 金額
        - 相談方式
        - チャットorビデオ電話
    end note
}
package プラン一覧集約{
    object プラン一覧{
        - タイトル
        - カテゴリ
        - タグ
        - 内容
        - ステータス
        - ユーザーID
        - 料金体系
        - 相談方式
        - メンターユーザ名
        - ページネーション20件
    }

    note right of プラン一覧
        - タイトル
        - カテゴリ
        - タグ
        - 内容
        - ステータス
        - 料金体系
        - 相談方式
        - プランを作成したユーザ名
        - ステータスが「中止」となっていないものだけ表示する
        - ページネーション20件
    end note
}
package 契約リクエスト集約{
object 契約リクエスト{
        - ユーザーID
        - メッセージ
        - プランのID
        - リクエスト金額
    }
}
package 契約集約{
    object 契約{
        - ユーザーID
        - メンターID
        - プランID
        - メンターID
        - メッセージ
    }
}

追加----- メンター募集
追加----- 契約
追加------メンター提案
追加---- プラン作成
追加------契約リクエスト
追加 "1"--* "0..*" career
追加 "1"--* "1..*" skill
契約リクエスト ------プラン一覧
契約リクエスト ------ プラン作成
契約 ----- プラン作成
メンター募集------ メンター提案
更新 "1"--* "0..*" updateCareer
更新 "1"--* "1..*" updateSkill
更新 --- 追加
@enduml
